### ISSUE TITLE
단짝 관리 페이지 수정

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Samcho#109]
## 📄 설명
교환 요청은 알림 버블창에서 수락 거절 받기로 하였으므로 토글 탭 컴포넌트 없애고 현재 단짝을 맺은 리스트만 보이도록 변경

## 📋 TO-DO
- [x] 단짝 관리 페이지 수정

## 🔔 기타
기타 사항을 적어주세요.

**Comment by paintover** [comment]
이슈 98번에서 같이 수정했습니다!
