### ISSUE TITLE
마이페이지에서 계정/모아보기 메뉴 컴포넌트 전체에 Link 처리

### ISSUE THREAD

**Issue by heydoopal** [FRONTENDSCHOOL10/Samcho#242]
## 📄 설명

![image](https://github.com/user-attachments/assets/530f0561-367c-4879-a1b8-166615461310)
마이페이지에서 계정 / 사진 모아보기 박스 클릭 시  `>`  버튼을 클릭시에만 화면 이동되고 있음

![image](https://github.com/user-attachments/assets/ac0e4be8-a344-4b49-b2cf-3ff35f84559e)
이렇게 전체를 클릭 해도 이동 되도록 수정하기

## 📋 TO-DO

- [ ] 계정 / 사진 모아보기 박스 전체에 링크 속성을 걸어 주기

## 🔔 기타

기타 사항을 적어주세요.

**Comment by devHyeon99** [comment]
해당 이슈 진행 보류
